name: compcert_benchmark_train
num_files: 164
language: COQ
few_shot_data_path_for_retrieval: .log/tools/coq_raw_proofs/data/benchmarks/CompCert/2023-09-06-03-44-06/CompCert/train
few_shot_metadata_filename_for_retrieval: single.meta.json
dfs_data_path_for_retrieval: .log/run_data_generation_transforms/data/benchmarks/CompCert/train
dfs_metadata_filename_for_retrieval: local.meta.json
setup_cmds:
  - opam env --switch=CompCert --set-switch
datasets:
  - project: <root>/data/repos/CompCert # data/benchmarks/CompCert
    files:
      - path: cfrontend/Cshmgen.v
        theorems:  "*"
      - path: cfrontend/Initializersproof.v
        theorems:  "*"
      - path: cfrontend/Csharpminor.v
        theorems:  "*"
      - path: cfrontend/Cstrategy.v
        theorems:  "*"
      - path: cfrontend/SimplLocalsproof.v
        theorems:  "*"
      - path: cfrontend/SimplExpr.v
        theorems:  "*"
      - path: cfrontend/Cexec.v
        theorems:  "*"
      - path: cfrontend/SimplExprspec.v
        theorems:  "*"
      - path: cfrontend/Initializers.v
        theorems:  "*"
      - path: cfrontend/Ctyping.v
        theorems:  "*"
      - path: cfrontend/Cminorgenproof.v
        theorems:  "*"
      - path: cfrontend/Csem.v
        theorems:  "*"
      - path: cfrontend/SimplExprproof.v
        theorems:  "*"
      - path: cfrontend/Cshmgenproof.v
        theorems:  "*"
      - path: cfrontend/ClightBigstep.v
        theorems:  "*"
      - path: cfrontend/Ctypes.v
        theorems:  "*"
      - path: cfrontend/SimplLocals.v
        theorems:  "*"
      - path: cfrontend/Csyntax.v
        theorems:  "*"
      - path: cfrontend/Clight.v
        theorems:  "*"
      - path: cfrontend/Cminorgen.v
        theorems:  "*"
      - path: MenhirLib/Automaton.v
        theorems:  "*"
      - path: MenhirLib/Validator_classes.v
        theorems:  "*"
      - path: MenhirLib/Interpreter_correct.v
        theorems:  "*"
      - path: MenhirLib/Alphabet.v
        theorems:  "*"
      - path: MenhirLib/Interpreter.v
        theorems:  "*"
      - path: MenhirLib/Main.v
        theorems:  "*"
      - path: MenhirLib/Grammar.v
        theorems:  "*"
      - path: MenhirLib/Validator_safe.v
        theorems:  "*"
      - path: MenhirLib/Interpreter_complete.v
        theorems:  "*"
      - path: x86_64/Archi.v
        theorems:  "*"
      - path: cparser/Cabs.v
        theorems:  "*"
      - path: flocq/Prop/Plus_error.v
        theorems:  "*"
      - path: flocq/Prop/Round_odd.v
        theorems:  "*"
      - path: flocq/Prop/Div_sqrt_error.v
        theorems:  "*"
      - path: flocq/Prop/Double_rounding.v
        theorems:  "*"
      - path: flocq/Prop/Relative.v
        theorems:  "*"
      - path: flocq/Prop/Sterbenz.v
        theorems:  "*"
      - path: flocq/Calc/Operations.v
        theorems:  "*"
      - path: flocq/Calc/Bracket.v
        theorems:  "*"
      - path: flocq/Calc/Sqrt.v
        theorems:  "*"
      - path: flocq/Calc/Div.v
        theorems:  "*"
      - path: flocq/IEEE754/Binary.v
        theorems:  "*"
      - path: flocq/IEEE754/Bits.v
        theorems:  "*"
      - path: flocq/Core/FTZ.v
        theorems:  "*"
      - path: flocq/Core/FLX.v
        theorems:  "*"
      - path: flocq/Core/Generic_fmt.v
        theorems:  "*"
      - path: flocq/Core/Core.v
        theorems:  "*"
      - path: flocq/Core/Digits.v
        theorems:  "*"
      - path: flocq/Core/Round_pred.v
        theorems:  "*"
      - path: flocq/Core/Round_NE.v
        theorems:  "*"
      - path: flocq/Core/FIX.v
        theorems:  "*"
      - path: flocq/Core/FLT.v
        theorems:  "*"
      - path: flocq/Core/Raux.v
        theorems:  "*"
      - path: flocq/Core/Float_prop.v
        theorems:  "*"
      - path: flocq/Core/Defs.v
        theorems:  "*"
      - path: flocq/Core/Ulp.v
        theorems:  "*"
      - path: x86/Conventions1.v
        theorems:  "*"
      - path: x86/CombineOp.v
        theorems:  "*"
      - path: x86/ConstpropOp.v
        theorems:  "*"
      - path: x86/ConstpropOpproof.v
        theorems:  "*"
      - path: x86/Asmgen.v
        theorems:  "*"
      - path: x86/NeedOp.v
        theorems:  "*"
      - path: x86/ValueAOp.v
        theorems:  "*"
      - path: x86/Builtins1.v
        theorems:  "*"
      - path: x86/Machregs.v
        theorems:  "*"
      - path: x86/Asmgenproof1.v
        theorems:  "*"
      - path: x86/SelectOp.v
        theorems:  "*"
      - path: x86/SelectLongproof.v
        theorems:  "*"
      - path: x86/CombineOpproof.v
        theorems:  "*"
      - path: x86/Op.v
        theorems:  "*"
      - path: x86/SelectLong.v
        theorems:  "*"
      - path: x86/Asmgenproof.v
        theorems:  "*"
      - path: x86/Stacklayout.v
        theorems:  "*"
      - path: x86/Asm.v
        theorems:  "*"
      - path: backend/Mach.v
        theorems:  "*"
      - path: backend/Constprop.v
        theorems:  "*"
      - path: backend/RTLgen.v
        theorems:  "*"
      - path: backend/RTLgenproof.v
        theorems:  "*"
      - path: backend/ValueDomain.v
        theorems:  "*"
      - path: backend/RTLgenspec.v
        theorems:  "*"
      - path: backend/Renumber.v
        theorems:  "*"
      - path: backend/Tunnelingproof.v
        theorems:  "*"
      - path: backend/Linear.v
        theorems:  "*"
      - path: backend/Liveness.v
        theorems:  "*"
      - path: backend/Inliningspec.v
        theorems:  "*"
      - path: backend/SplitLongproof.v
        theorems:  "*"
      - path: backend/Stacking.v
        theorems:  "*"
      - path: backend/Debugvarproof.v
        theorems:  "*"
      - path: backend/CSE.v
        theorems:  "*"
      - path: backend/Asmgenproof0.v
        theorems:  "*"
      - path: backend/Allocation.v
        theorems:  "*"
      - path: backend/Selection.v
        theorems:  "*"
      - path: backend/Renumberproof.v
        theorems:  "*"
      - path: backend/Conventions.v
        theorems:  "*"
      - path: backend/LTL.v
        theorems:  "*"
      - path: backend/Inlining.v
        theorems:  "*"
      - path: backend/Linearizeproof.v
        theorems:  "*"
      - path: backend/Linearize.v
        theorems:  "*"
      - path: backend/Stackingproof.v
        theorems:  "*"
      - path: backend/SplitLong.v
        theorems:  "*"
      - path: backend/Deadcodeproof.v
        theorems:  "*"
      - path: backend/Tailcall.v
        theorems:  "*"
      - path: backend/CSEproof.v
        theorems:  "*"
      - path: backend/ValueAnalysis.v
        theorems:  "*"
      - path: backend/Registers.v
        theorems:  "*"
      - path: backend/Unusedglob.v
        theorems:  "*"
      - path: backend/Lineartyping.v
        theorems:  "*"
      - path: backend/Tunneling.v
        theorems:  "*"
      - path: backend/Unusedglobproof.v
        theorems:  "*"
      - path: backend/SelectDivproof.v
        theorems:  "*"
      - path: backend/Deadcode.v
        theorems:  "*"
      - path: backend/CleanupLabels.v
        theorems:  "*"
      - path: backend/Cminortyping.v
        theorems:  "*"
      - path: backend/CleanupLabelsproof.v
        theorems:  "*"
      - path: backend/SelectDiv.v
        theorems:  "*"
      - path: backend/Tailcallproof.v
        theorems:  "*"
      - path: backend/Allocproof.v
        theorems:  "*"
      - path: backend/Constpropproof.v
        theorems:  "*"
      - path: backend/CminorSel.v
        theorems:  "*"
      - path: backend/NeedDomain.v
        theorems:  "*"
      - path: backend/Kildall.v
        theorems:  "*"
      - path: backend/RTLtyping.v
        theorems:  "*"
      - path: backend/Bounds.v
        theorems:  "*"
      - path: backend/Cminor.v
        theorems:  "*"
      - path: backend/Inliningproof.v
        theorems:  "*"
      - path: backend/CSEdomain.v
        theorems:  "*"
      - path: backend/Debugvar.v
        theorems:  "*"
      - path: common/Events.v
        theorems:  "*"
      - path: common/Behaviors.v
        theorems:  "*"
      - path: common/Memory.v
        theorems:  "*"
      - path: common/Values.v
        theorems:  "*"
      - path: common/Builtins0.v
        theorems:  "*"
      - path: common/Smallstep.v
        theorems:  "*"
      - path: common/Memtype.v
        theorems:  "*"
      - path: common/Switch.v
        theorems:  "*"
      - path: common/Linking.v
        theorems:  "*"
      - path: common/Unityping.v
        theorems:  "*"
      - path: common/Separation.v
        theorems:  "*"
      - path: common/Memdata.v
        theorems:  "*"
      - path: common/Determinism.v
        theorems:  "*"
      - path: common/Builtins.v
        theorems:  "*"
      - path: common/AST.v
        theorems:  "*"
      - path: common/Errors.v
        theorems:  "*"
      - path: driver/Complements.v
        theorems:  "*"
      - path: driver/Compopts.v
        theorems:  "*"
      - path: driver/Compiler.v
        theorems:  "*"
      - path: lib/Zbits.v
        theorems:  "*"
      - path: lib/Ordered.v
        theorems:  "*"
      - path: lib/Lattice.v
        theorems:  "*"
      - path: lib/IEEE754_extra.v
        theorems:  "*"
      - path: lib/Coqlib.v
        theorems:  "*"
      - path: lib/FSetAVLplus.v
        theorems:  "*"
      - path: lib/IntvSets.v
        theorems:  "*"
      - path: lib/BoolEqual.v
        theorems:  "*"
      - path: lib/Iteration.v
        theorems:  "*"
      - path: lib/Floats.v
        theorems:  "*"
      - path: lib/UnionFind.v
        theorems:  "*"
      - path: lib/Decidableplus.v
        theorems:  "*"
      - path: lib/Integers.v
        theorems:  "*"
      - path: lib/Heaps.v
        theorems:  "*"
      - path: lib/Maps.v
        theorems:  "*"
      - path: lib/Postorder.v
        theorems:  "*"
      - path: lib/Axioms.v
        theorems:  "*"
      - path: lib/Intv.v
        theorems:  "*"