name: putnambench_lean_ext
num_files: 1
language: LEAN4
few_shot_data_path_for_retrieval: 
few_shot_metadata_filename_for_retrieval: 
dfs_data_path_for_retrieval: 
dfs_metadata_filename_for_retrieval: 
is_extraction_request: true
datasets:
  - project: src/data/test/PutnamBench/lean4
    files: []
    exclude_files:
      - src/data/test/PutnamBench/lean4/.lake
      - src/data/test/PutnamBench/lean4/src
      - src/data/test/PutnamBench/lean4/check_docstrings.lean
      - src/data/test/PutnamBench/lean4/lakefile.lean