defaults:
  # - benchmark: simple_benchmark_lean_training_data
  # - run_settings: default_lean_data_generation_transforms
  - benchmark: leandojo_random_train
  - run_settings: default_lean4_data_generation_transforms
  - env_settings: no_retrieval
  - override hydra/job_logging: 'disabled'

run_settings:
 output_dir: <root>/data/proofsteps/mathlib
#  train_eval_test_split:
#    - 0.925
#    - 0.0375
#    - 0.0375