defaults:
  # - benchmark: simple_benchmark_lean_training_data
  # - run_settings: default_lean_data_generation_transforms
  - benchmark: category-theory
  - run_settings: default_coq_data_generation_transforms
  - env_settings: no_retrieval
  - override hydra/job_logging: 'disabled'

run_settings:
 output_dir: /mnt/amthakur/data/proofsteps/random-small-test/category-theory
 random_split: True
 random_seed: 0xf00
 train_eval_test_split:
   - 0.9625
   - 0.01875
   - 0.01875