defaults:
  - benchmark: simple_benchmark_lean_training_data
  - run_settings: default_lean_data_generation_transforms
  # - benchmark: simple_benchmark_1
  # - run_settings: default_coq_data_generation_transforms
  - env_settings: bm25_retrieval
  - override hydra/job_logging: 'disabled'