defaults:
  # - benchmark: simple_benchmark_lean_training_data
  # - run_settings: default_lean_data_generation_transforms
  - benchmark: GeoCoq
  - run_settings: default_coq_data_generation_transforms
  - env_settings: no_retrieval
  - override hydra/job_logging: 'disabled'

run_settings:
 output_dir: <root>/data/proofsteps/random-small-test/GeoCoq
 random_split: True
 random_seed: 0xf00
 train_eval_test_split:
   - 0.8500
   - 0.0439
   - 0.1061