name: simple_benchmark_isabelle
num_files: 1
language: ISABELLE
few_shot_data_path_for_retrieval: 
few_shot_metadata_filename_for_retrieval: 
dfs_data_path_for_retrieval: 
dfs_metadata_filename_for_retrieval: 
datasets:
  - project: data/test/isabelle/custom_hol
    files:
      - path: Basic_Logic.thy
        theorems: "*"
      - path: Basic_Logic2.thy
        theorems: "*"
  - project: <root>/data/repos/AFP/afp-2022-12-06/thys/FunWithFunctions
    files:
      - path: FunWithFunctions.thy
        theorems: "*"
